---
title: "TD6"
author: "Perrin Kyllian"
date: "7 mars 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr);
library(magrittr);
library(ggplot2);
library(dplyr);
```

```{r}
dice <- function(faces = 6, n = 100){
  sample(x = seq(from = 1, to = faces, by = 1),size=n,replace=TRUE);
}
```

```{r}
dice(6,600);

```

```{r}
experiment <- function (faces = 6, n = 100){
  dice1<-dice(faces,n);
  dice2<-dice(faces,n);
  dice3<-dice(faces,n);
  data.frame(Dice1=dice1,
             Dice2=dice2,
             Dice3=dice3)
}
```

```{r}
N=50000
rolls <- experiment(6,N);
result <- rolls %>% mutate(Sum = Dice1+Dice2+Dice3);
final <- result %>% group_by(Sum) %>% summarize(nbocc=n());
final
```

```{r}
ggplot(data=result,aes(x=as.factor(Sum)))+
geom_bar(aes(y= (..count..)/sum(..count..)), width =.3)+
xlab("Valeur") +
ylab("Nombre d'occurence")+
theme_bw();
```

```{r}
Echant = final %>% mutate(freq = nbocc/N) %>% mutate(var= freq*(1-freq)) %>% mutate(error = (qnorm(0.95)*sqrt(var))/sqrt(N));
Echant
```

```{r}
ggplot(data=Echant, aes(x=freq, y=Sum,xmin = freq-error, xmax= freq+error))+
  geom_errorbarh()+
  theme_bw()
```

```{r}

```

```{r}

```
